export const navMenu = [
  {
    title: "Store",
    links: [
      { text: "Explore All Products", href: "./" },
      { text: "Mac", href: "/" },
      { text: "iPad", href: "/" },
      { text: "iPhone", href: "/" },
      { text: "Watch", href: "/" },
      { text: "Vision", href: "/" },
      { text: "AirPods", href: "/" },
      { text: "TV & Home", href: "/" },
      { text: "Accessories", href: "/" },
      { text: "Gift Cards", href: "/" },
    ],
  },
  {
    title: "Mac",
    links: [
      { text: "MacBook Air", href: "/" },
      { text: "MacBook Pro", href: "/" },
      { text: "iMac", href: "/" },
      { text: "Mac mini", href: "/" },
      { text: "Mac Studio", href: "/" },
      { text: "Mac Pro", href: "/" },
      { text: "Displays", href: "/" },
      { text: "Compare", href: "/" },
      { text: "Accessories", href: "/" },
      { text: "Apple Silicon", href: "/" },
      { text: "macOS", href: "/" },
    ],
  },
  {
    title: "iPad",
    links: [
      { text: "iPad Pro", href: "/" },
      { text: "iPad Air", href: "/" },
      { text: "iPad", href: "/" },
      { text: "iPad mini", href: "/" },
      { text: "Compare", href: "/" },
      { text: "Apple Pencil", href: "/" },
      { text: "Keyboards", href: "/" },
      { text: "Accessories", href: "/" },
      { text: "iPadOS", href: "/" },
    ],
  },
  {
    title: "iPhone",
    links: [
      { text: "iPhone 16 Pro", href: "./" },
      { text: "iPhone 16", href: "./" },
      { text: "iPhone 15", href: "./" },
      { text: "iPhone SE", href: "./" },
      { text: "Compare", href: "./" },
      { text: "AirTag", href: "./" },
      { text: "Accessories", href: "./" },
      { text: "iOS", href: "./" },
    ],
  },
  {
    title: "Watch",
    links: [
      { text: "Apple Watch Series 10", href: "./" },
      { text: "Apple Watch SE", href: "./" },
      { text: "Apple Watch Ultra", href: "./" },
      { text: "Compare", href: "./" },
      { text: "Bands", href: "./" },
      { text: "Accessories", href: "./" },
      { text: "watchOS", href: "./" },
    ],
  },
  {
    title: "Vision",
    links: [
      { text: "Apple Vision Pro", href: "./" },
      { text: "Features", href: "./" },
      { text: "Apps", href: "./" },
      { text: "Tech Specs", href: "./" },
    ],
  },
  {
    title: "AirPods",
    links: [
      { text: "AirPods Pro (2nd generation)", href: "./" },
      { text: "AirPods (3rd generation)", href: "./" },
      { text: "AirPods Max", href: "./" },
      { text: "AirPods (2nd generation)", href: "./" },
      { text: "Compare", href: "./" },
      { text: "Accessories", href: "./" },
    ],
  },
  {
    title: "TV & Home",
    links: [
      { text: "Apple TV 4K", href: "./" },
      { text: "Apple TV HD", href: "./" },
      { text: "HomePod", href: "./" },
      { text: "HomePod mini", href: "./" },
      { text: "Siri Remote", href: "./" },
      { text: "AirPlay", href: "./" },
      { text: "Accessories", href: "./" },
      { text: "Home app", href: "./" },
    ],
  },
  {
    title: "Entertainment",
    links: [
      { text: "Apple One", href: "./" },
      { text: "Apple TV+", href: "./" },
      { text: "Apple Music", href: "./" },
      { text: "Apple Arcade", href: "./" },
      { text: "Apple Fitness+", href: "./" },
      { text: "Apple News+", href: "./" },
      { text: "Apple Podcasts", href: "./" },
      { text: "Apple Books", href: "./" },
      { text: "App Store", href: "./" },
    ],
  },
  {
    title: "Accessories",
    links: [
      { text: "Explore All Accessories", href: "./" },
      { text: "Mac Accessories", href: "./" },
      { text: "iPad Accessories", href: "./" },
      { text: "iPhone Accessories", href: "./" },
      { text: "Apple Watch Accessories", href: "./" },
      { text: "AirTag", href: "./" },
      { text: "TV & Home Accessories", href: "./" },
      { text: "Featured Accessories", href: "./" },
    ],
  },
  {
    title: "Support",
    links: [
      { text: "Support Home", href: "./" },
      { text: "iPhone Support", href: "./" },
      { text: "Mac Support", href: "./" },
      { text: "iPad Support", href: "./" },
      { text: "Watch Support", href: "./" },
      { text: "AirPods Support", href: "./" },
      { text: "Music Support", href: "./" },
      { text: "TV Support", href: "./" },
      { text: "Support by Product", href: "./" },
      { text: "Account Support", href: "./" },
      { text: "Contact Support", href: "./" },
    ],
  },
];
